/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.antifraud.domain.tables.records;


import com.rbkmoney.antifraud.domain.tables.Payment;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record14;
import org.jooq.Record2;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentRecord extends UpdatableRecordImpl<PaymentRecord> implements Record14<String, String, String, String, String, String, String, String, String, Long, String, String, String, String> {

    private static final long serialVersionUID = -60970939;

    /**
     * Setter for <code>af.payment.invoice_id</code>.
     */
    public void setInvoiceId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>af.payment.invoice_id</code>.
     */
    public String getInvoiceId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>af.payment.payment_id</code>.
     */
    public void setPaymentId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>af.payment.payment_id</code>.
     */
    public String getPaymentId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>af.payment.party_id</code>.
     */
    public void setPartyId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>af.payment.party_id</code>.
     */
    public String getPartyId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>af.payment.shop_id</code>.
     */
    public void setShopId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>af.payment.shop_id</code>.
     */
    public String getShopId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>af.payment.client_ip</code>.
     */
    public void setClientIp(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>af.payment.client_ip</code>.
     */
    public String getClientIp() {
        return (String) get(4);
    }

    /**
     * Setter for <code>af.payment.client_email</code>.
     */
    public void setClientEmail(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>af.payment.client_email</code>.
     */
    public String getClientEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>af.payment.client_fingerprint</code>.
     */
    public void setClientFingerprint(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>af.payment.client_fingerprint</code>.
     */
    public String getClientFingerprint() {
        return (String) get(6);
    }

    /**
     * Setter for <code>af.payment.card_mask</code>.
     */
    public void setCardMask(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>af.payment.card_mask</code>.
     */
    public String getCardMask() {
        return (String) get(7);
    }

    /**
     * Setter for <code>af.payment.card_token</code>.
     */
    public void setCardToken(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>af.payment.card_token</code>.
     */
    public String getCardToken() {
        return (String) get(8);
    }

    /**
     * Setter for <code>af.payment.amount</code>.
     */
    public void setAmount(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>af.payment.amount</code>.
     */
    public Long getAmount() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>af.payment.currency</code>.
     */
    public void setCurrency(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>af.payment.currency</code>.
     */
    public String getCurrency() {
        return (String) get(10);
    }

    /**
     * Setter for <code>af.payment.description</code>.
     */
    public void setDescription(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>af.payment.description</code>.
     */
    public String getDescription() {
        return (String) get(11);
    }

    /**
     * Setter for <code>af.payment.shop_name</code>.
     */
    public void setShopName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>af.payment.shop_name</code>.
     */
    public String getShopName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>af.payment.shop_url</code>.
     */
    public void setShopUrl(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>af.payment.shop_url</code>.
     */
    public String getShopUrl() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<String, String, String, String, String, String, String, String, String, Long, String, String, String, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<String, String, String, String, String, String, String, String, String, Long, String, String, String, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Payment.PAYMENT.INVOICE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Payment.PAYMENT.PAYMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Payment.PAYMENT.PARTY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Payment.PAYMENT.SHOP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Payment.PAYMENT.CLIENT_IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Payment.PAYMENT.CLIENT_EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Payment.PAYMENT.CLIENT_FINGERPRINT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Payment.PAYMENT.CARD_MASK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Payment.PAYMENT.CARD_TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return Payment.PAYMENT.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Payment.PAYMENT.CURRENCY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Payment.PAYMENT.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Payment.PAYMENT.SHOP_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Payment.PAYMENT.SHOP_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getInvoiceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPaymentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPartyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getShopId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getClientIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getClientEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getClientFingerprint();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCardMask();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCardToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getShopName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getShopUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value1(String value) {
        setInvoiceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value2(String value) {
        setPaymentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value3(String value) {
        setPartyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value4(String value) {
        setShopId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value5(String value) {
        setClientIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value6(String value) {
        setClientEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value7(String value) {
        setClientFingerprint(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value8(String value) {
        setCardMask(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value9(String value) {
        setCardToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value10(Long value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value11(String value) {
        setCurrency(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value12(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value13(String value) {
        setShopName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value14(String value) {
        setShopUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, Long value10, String value11, String value12, String value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaymentRecord
     */
    public PaymentRecord() {
        super(Payment.PAYMENT);
    }

    /**
     * Create a detached, initialised PaymentRecord
     */
    public PaymentRecord(String invoiceId, String paymentId, String partyId, String shopId, String clientIp, String clientEmail, String clientFingerprint, String cardMask, String cardToken, Long amount, String currency, String description, String shopName, String shopUrl) {
        super(Payment.PAYMENT);

        set(0, invoiceId);
        set(1, paymentId);
        set(2, partyId);
        set(3, shopId);
        set(4, clientIp);
        set(5, clientEmail);
        set(6, clientFingerprint);
        set(7, cardMask);
        set(8, cardToken);
        set(9, amount);
        set(10, currency);
        set(11, description);
        set(12, shopName);
        set(13, shopUrl);
    }
}
