/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.antifraud.domain;


import com.rbkmoney.antifraud.domain.tables.Payment;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in af
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>af.payment</code>.
     */
    public static final Payment PAYMENT = com.rbkmoney.antifraud.domain.tables.Payment.PAYMENT;
}
