CREATE SCHEMA if NOT EXISTS af;

CREATE TABLE af.payment (
  invoice_id CHARACTER VARYING NOT NULL,
  payment_id  CHARACTER VARYING NOT NULL,
  party_id CHARACTER VARYING NOT NULL,
  shop_id  CHARACTER VARYING NOT NULL,
  client_ip  CHARACTER VARYING NOT NULL,
  client_email  CHARACTER VARYING NOT NULL,
  client_fingerprint CHARACTER VARYING NOT NULL,
  card_mask CHARACTER VARYING NOT NULL,
  card_token CHARACTER VARYING NOT NULL,
  amount BIGINT NOT NULL,
  currency CHARACTER VARYING NOT NULL,
  description CHARACTER VARYING NOT NULL,
  shop_name  CHARACTER VARYING NOT NULL,
  shop_url  CHARACTER VARYING NOT NULL,
  CONSTRAINT payment_pkey PRIMARY KEY (invoice_id, payment_id)
);